### ISSUE TITLE
Add Beam "energymin" and "energymax" to main output

### ISSUE THREAD

**Issue by ChristopherMayes** [svenreiche/Genesis-1.3-Version4#102]
It is useful to see the minimum and maximum particle energy in the main output. Could we add:
- `Beam/energymin`: minimum particle energy in a slice
- `Beam/energymax`: maximum particle energy in a slice
Similarly, it would be useful to have the same for `x`, `px`, `y`, and `py`. 

**Describe alternatives you've considered**
The only alternative is to dump particles on regular intervals and inspect them, which is slow.

**Comment by svenreiche** [comment]
I will add them soon since it is rather easy to implement.

**Comment by svenreiche** [comment]
Minimum and maximum value for x,px,y,py and energy have been added to the output. For large files this output can be suppresed with enable_aux_output = False in the main setup deck.  The addition is in the current dev branch but will be transferred to the master branch with a new release.
