### ISSUE TITLE
[BUG] Generated particles do not honor the requested bunching

### ISSUE THREAD

**Issue by ChristopherMayes** [svenreiche/Genesis-1.3-Version4#136]
**Describe the bug**
Above some value for bunching, the particles that Genesis4 produces do not show the requested level. Scanning over several values shows:

<img width="436" alt="image" src="https://github.com/svenreiche/Genesis-1.3-Version4/assets/31023527/d8ceb244-ec23-4483-adb0-051042b505dc">

**To Reproduce**
Using the following input, the bunching from the particles is 0.44 and not 0.5 as requested.  The distribution in a typical slice looks like:
<img width="564" alt="image" src="https://github.com/svenreiche/Genesis-1.3-Version4/assets/31023527/07197c9e-1625-445d-b96f-622456a13adc">

```
&setup
rootname = drift_test
lattice = genesis4_drift.lat
beamline = LAT
lambda0 = 1e-07
gamma0 = 1000
seed = 123456
&end

&time
slen = 100e-7
sample = 1
&end

&beam
current = 1000
gamma = 1000
delgam = 1
bunch = 0.5
&end

&track
zstop = 1e-09
&end

&write
beam = end
&end
```

with `genesis4_drift.lat`:
```

D1: DRIFT = { L= 1e-9 };
LAT: LINE= { D1 };
```

**Expected behavior**
Bunching equal to the request is expected.

**Comment by ChristopherMayes** [comment]
The code that does this is: https://github.com/svenreiche/Genesis-1.3-Version4/blob/694c1d0c7d9d6a49f93e88ecc5629f9f4d970bce/src/Loading/QuietLoading.cpp#L258

Integrating gives the bunching = $J_1(2b)$, 

<img width="452" alt="image" src="https://github.com/svenreiche/Genesis-1.3-Version4/assets/31023527/50972682-6d04-479f-8f3d-49ee1281fccd">

**Comment by svenreiche** [comment]
The loading algorithm has been fixed and can now reproduce bunching factors up to 1.  
To keep some back-compatibilities the correction is only applied for requested bunching values above 0.1
The updated code has been committed to master and dev branch
