### ISSUE TITLE
[BUG] Error when dumping electron beam when one4one = false

### ISSUE THREAD

**Issue by nrt63** [svenreiche/Genesis-1.3-Version4#139]
**Describe the bug**

Version 4.6.5. Error reported with writing particle distributions to file:
 
***************
Writing particle distribution to file: SXR_SSEEDING_MOD1.par.h5 ...
terminate called after throwing an instance of 'std::out_of_range'
what():  vector::_M_range_check: __n (which is 2048) >= this->size() (which is 2048)
*******************

This error only occurs when one4one = false

**To Reproduce**
Input file code:

-------------------------------------------------
&setup
.
.
npart = 2048
one4one = false
.
.
&end

&write
beam=SXR_SSEEDING_MOD1
&end

&track
beam_dump_step=278
&end
-----------------------------------------

**Expected behavior**
Writing of a .par.hr file

**Additional context**
Apologies if user error!

**Comment by nrt63** [comment]
Edit - problem also occurs when one4one = true. Title of issue amended.

**Comment by svenreiche** [comment]
I ran some test files with the latest version and I have no crash.
As mentioned before it is the bug which has been only fixed last week.

Can you check on your side with the latest git commit of the master branch?

Best
Sven

**Comment by svenreiche** [comment]
HAs been verified that the problem is solved with the recent commit to fix the problem with dumping the particles
