### ISSUE TITLE
value of variable 'transfer' in src/Util/Sorting.cpp

### ISSUE THREAD

**Issue by bellaz89** [svenreiche/Genesis-1.3-Version4#14]
The variable 'transfer' of Sorting::globalSort is compared to 'true' at line 180:

https://github.com/svenreiche/Genesis-1.3-Version4/blob/c7125f4bedfb34691706911e736d88853424b829/src/Util/Sorting.cpp#L180

Such a statement has no effect. 
Was it supposed to do an assignment (=) instead of a comparison (==)?

**Comment by svenreiche** [comment]
Thank you for finding the bug. This should indeed be just a simple assignment. The bug would obly be visible if genesis is run with an odd number of cores and sorting. I pushed to github the new version.
