### ISSUE TITLE
[ISSUE] Problem with labels using sequences 

### ISSUE THREAD

**Issue by mgracia9** [svenreiche/Genesis-1.3-Version4#164]
I would like to report an issue with the current version of Genesis. I tried to use  &sequence_const. I set the label name to label=test  and &lattice value = @test, when running the code .. i get the error:

_Unknown Sequence reference in &lattice: test._

I tried to run the Aramis.in as well from the benchmark/Benchmark4-UndErrors folder and I get the same error. 

In an older version of the code, both the Benchmark4-UndErrors and my input file works. 

(For reference, the older version of genesis was compiled and ran in a ubuntu-22.04 machine, the newer one that it is failing in MacOs-sonoma 14.1).

**Comment by ZeugAusHH** [comment]
Dear @mgracia9 ,

could you please provide us with:
- a minimum working example demonstrating the issue and
- the git commit IDs reported at start by both the "older" and the "newer" versions of genesis you are referring to?

Many thanks

**Comment by svenreiche** [comment]
I tested with the recent master branch and it works for me. I cannot reproduce the error.
Note that the lattice is already parsed in the setup namelist, so you have to put the sequence definition before the set-up to make it work.

Best
Sven

-----------------------------
Input deck is:

&sequence_const
label = test
c0 = 0.84853
&end

&setup
rootname=Example1
lattice=Example1.lat
beamline=FEL
lambda0=1e-10
gamma0=11357.82
delz=0.045000
shotnoise=0
nbins = 8
&end
....

and the lattice file:

D1: DRIFT = { l = 0.44};
D2: DRIFT = { l = 0.24};
QF: QUADRUPOLE = { l = 0.080000, k1= 2.000000 };
QD: QUADRUPOLE = { l = 0.080000, k1= -2.000000 };
UND: UNDULATOR = { lambdau=0.015000, nwig=266, aw= @test, helical= True};
COR: CORRECTOR = { l = 0.24, cx = 1e-6};
FODO: LINE={UND,D1,QF,D2,UND,D1,QD,COR};

FEL: LINE={6*FODO};

and I am getting the desired value for aw.

Output: 
Opened input file Test.in
Adding sequence with label: test
Parsing lattice file Example1.lat ...
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***
*** Ref to series test, result is: aw=0.85853 ***

**Comment by svenreiche** [comment]
This I can reproduce. I will have a look into it

Sven

**Comment by svenreiche** [comment]
I fixed the error and released a new master branch.
I would like to mention that the feature of using the lattice namelist to alter values of the lattice will become obsolete in the future since it is much easier to include the reference to the sequence directly in the lattice file as shown in my first message in this thread.
