### ISSUE TITLE
beam_global_stat & field_global_stat not writing data for beam with step profile

### ISSUE THREAD

**Issue by nrt63** [svenreiche/Genesis-1.3-Version4#173]
When setting a step current profile, e.g.

&profile_step
label=prof2
c0=2200
s_start=1e-6
s_end=7e-6
&end

with 

beam_global_stat=true
field_global_stat=true

the output fields Beam/Global/xsize etc and Field/Global/xsize contain only a single value at z = 0 and all other values are NaN. 

Expected behaviour, for example if using using a gaussian profile, is that Beam/Global/xsize etc and Field/Global/xsize etc have different numerical values at every z step.

**Comment by ZeugAusHH** [comment]
Hi @nrt63 ,

could you please provide a minimum working example demonstrating the issue? Which version of Genesis are you using -- ideally please provide the git commit id of the source code.

Many thanks

**Comment by nrt63** [comment]
Version is 4.6.5.

 Input file and lattice file attached. 
Change between current = @prof1 and @prof2 to see effect. 
[FEL2_10keV.lat.txt](https://github.com/svenreiche/Genesis-1.3-Version4/files/15393351/FEL2_10keV.lat.txt)
[FEL2_10keV_TD.in.txt](https://github.com/svenreiche/Genesis-1.3-Version4/files/15393352/FEL2_10keV_TD.in.txt)

Thanks

**Comment by nrt63** [comment]
Can provide git commit id tomorrow if needed.

**Comment by nrt63** [comment]
Compiled by jkj62 at 2024-01-10 15:16:43 [UTC] 
Git Commit ID: d475c5627f831b2a82cf4279bb1e3769cc2c9d6e

**Comment by svenreiche** [comment]
I will look at this week. I think the problem is the same as I encounter Nan values for energy etc if I am using a step-profile. Then the global stat would make no sense.

**Comment by svenreiche** [comment]
Fixed. Problem was in the generation of shot noise for a strictly zero current beam, which is ill-defined. Latest release should have no further issues with it
