### ISSUE TITLE
Errors compiling on MacOsX High Sierra

### ISSUE THREAD

**Issue by Garzik** [svenreiche/Genesis-1.3-Version4#28]
**Trying to compile Genesis-1.3-Version4-master on MacOsX High Sierra.
CLANG version : Apple LLVM version 10.0.0 (clang-1000.10.44.4).

Upon 'make' command, here is the result :**  

h5pcc -O2 -c -DAAAFFTW -I./include src/Util/Sorting.cpp
In file included from src/Util/Sorting.cpp:1:
In file included from ./include/Sorting.h:4:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iostream:38:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ios:215:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:90:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:119:
In file included from /usr/include/wchar.h:91:
In file included from ./include/time.h:5:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/vector:266:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__bit_reference:15:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:643:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/memory:659:
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:877:27: error: no template named 'char_traits'
          class _Traits = char_traits<_CharT>, class _Distance = ptrdiff_t>
                          ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:877:17: error: template parameter missing a
      default argument
          class _Traits = char_traits<_CharT>, class _Distance = ptrdiff_t>
                ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:876:37: note: previous default template argument
      defined here
template <class _Tp, class _CharT = char,
                                    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:884:13: error: no template named 'basic_istream'
    typedef basic_istream<_CharT,_Traits> istream_type;
            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:938:59: error: no template named 'char_traits'
template <class _Tp, class _CharT = char, class _Traits = char_traits<_CharT> >
                                                          ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:938:49: error: template parameter missing a
      default argument
template <class _Tp, class _CharT = char, class _Traits = char_traits<_CharT> >
                                                ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:938:37: note: previous default template argument
      defined here
template <class _Tp, class _CharT = char, class _Traits = char_traits<_CharT> >
                                    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:945:13: error: no template named 'basic_ostream'
    typedef basic_ostream<_CharT,_Traits> ostream_type;
            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:977:13: error: no template named 'basic_streambuf'
    typedef basic_streambuf<_CharT,_Traits> streambuf_type;
            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:978:13: error: no template named 'basic_istream'
    typedef basic_istream<_CharT,_Traits>   istream_type;
            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:996:56: error: member reference base type
      'std::__1::istreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
        if (__sbuf_ && traits_type::eq_int_type(__sbuf_->sgetc(), traits_type::eof()))
                                                ~~~~~~~^ ~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1003:22: error: member reference base type
      'std::__1::istreambuf_iterator::istream_type' (aka 'int') is not a structure or union
        : __sbuf_(__s.rdbuf()) {}
                  ~~~^~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1010:47: error: member reference base type
      'std::__1::istreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
        {return static_cast<char_type>(__sbuf_->sgetc());}
                                       ~~~~~~~^ ~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1013:20: error: member reference base type
      'std::__1::istreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
            __sbuf_->sbumpc();
            ~~~~~~~^ ~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1018:35: error: member reference base type
      'std::__1::istreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
            return __proxy(__sbuf_->sbumpc(), __sbuf_);
                           ~~~~~~~^ ~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1044:13: error: no template named
      'basic_streambuf'
    typedef basic_streambuf<_CharT,_Traits> streambuf_type;
            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1045:13: error: no template named 'basic_ostream'
    typedef basic_ostream<_CharT,_Traits>   ostream_type;
            ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1074:22: error: unknown type name 'ios_base'
                     ios_base& __iob, _Ch __fl);
                     ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1050:22: error: member reference base type
      'std::__1::ostreambuf_iterator::ostream_type' (aka 'int') is not a structure or union
        : __sbuf_(__s.rdbuf()) {}
                  ~~~^~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/iterator:1055:60: error: member reference base type
      'std::__1::ostreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
            if (__sbuf_ && traits_type::eq_int_type(__sbuf_->sputc(__c), traits_type::eof()))
                                                    ~~~~~~~^ ~~~~~
In file included from src/Util/Sorting.cpp:1:
In file included from ./include/Sorting.h:4:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iostream:38:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/ios:215:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/iosfwd:90:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/wchar.h:119:
In file included from /usr/include/wchar.h:91:
In file included from ./include/time.h:5:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/vector:266:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/__bit_reference:15:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/algorithm:643:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/memory:663:
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdexcept:83:32: error: unknown type name 'string'
    explicit logic_error(const string&);
                               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Sorting.o] Error 1

**Comment by messiahacc** [comment]
same error. have you fixed it?

**Comment by svenreiche** [comment]
Hmm,
the error is not much descriptive. I have to try to compile it on my mac to reproduce the error and then fix it.
Best
Sven

**Comment by Fumikac** [comment]
Hi I was wondering if this issue is resolved.

**Comment by svenreiche** [comment]
Sorry, in home office I do not have a good access to a mac system. I could verify the problem but this seems to be a generic problem with MacOSX to compile C++ programs since I am getting the error also for simple 'hello world' programs. I hope that once I figure out the compiler configuration it should work.

Best
Sven

**Comment by Garzik** [comment]
**Dear Sven,**

**one year after, trying again with last code release, and on MacOS Big Sur**
**Obtaining still almost the same errors on compilation :**

(base) MacBook-Pro-de-David:Genesis-1.3-Version4-4.5.1 david$ **make**
h5pcc -g -O2 -c -DFFTW  -I./include src/Util/Sorting.cpp
In file included from src/Util/Sorting.cpp:1:
In file included from ./include/Sorting.h:4:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:37:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:214:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:95:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/wchar.h:119:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wchar.h:91:
In file included from ./include/time.h:5:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:276:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__bit_reference:14:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/bit:61:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__debug:62:25: error: no type named 'string' in namespace 'std'
  _LIBCPP_FUNC_VIS std::string what() const;
                   ~~~~~^
In file included from src/Util/Sorting.cpp:1:
In file included from ./include/Sorting.h:4:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:37:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:214:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:95:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/wchar.h:119:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wchar.h:91:
In file included from ./include/time.h:5:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:276:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__bit_reference:15:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:643:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/memory:674:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:989:27: error: no template named 'char_traits'
          class _Traits = char_traits<_CharT>, class _Distance = ptrdiff_t>
                          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:989:17: error: template parameter missing a default argument
          class _Traits = char_traits<_CharT>, class _Distance = ptrdiff_t>
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:988:37: note: previous default template argument defined here
template <class _Tp, class _CharT = char,
                                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:996:13: error: no template named 'basic_istream'
    typedef basic_istream<_CharT,_Traits> istream_type;
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1050:59: error: no template named 'char_traits'
template <class _Tp, class _CharT = char, class _Traits = char_traits<_CharT> >
                                                          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1050:49: error: template parameter missing a default argument
template <class _Tp, class _CharT = char, class _Traits = char_traits<_CharT> >
                                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1050:37: note: previous default template argument defined here
template <class _Tp, class _CharT = char, class _Traits = char_traits<_CharT> >
                                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1066:13: error: no template named 'basic_ostream'
    typedef basic_ostream<_CharT, _Traits>  ostream_type;
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1099:13: error: no template named 'basic_streambuf'
    typedef basic_streambuf<_CharT,_Traits> streambuf_type;
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1100:13: error: no template named 'basic_istream'
    typedef basic_istream<_CharT,_Traits>   istream_type;
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1118:56: error: member reference base type 'std::istreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
        if (__sbuf_ && traits_type::eq_int_type(__sbuf_->sgetc(), traits_type::eof()))
                                                ~~~~~~~^ ~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1125:22: error: member reference base type 'std::istreambuf_iterator::istream_type' (aka 'int') is not a structure or union
        : __sbuf_(__s.rdbuf()) {}
                  ~~~^~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1132:47: error: member reference base type 'std::istreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
        {return static_cast<char_type>(__sbuf_->sgetc());}
                                       ~~~~~~~^ ~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1135:20: error: member reference base type 'std::istreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
            __sbuf_->sbumpc();
            ~~~~~~~^ ~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1140:35: error: member reference base type 'std::istreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
            return __proxy(__sbuf_->sbumpc(), __sbuf_);
                           ~~~~~~~^ ~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1175:13: error: no template named 'basic_streambuf'
    typedef basic_streambuf<_CharT, _Traits>    streambuf_type;
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1176:13: error: no template named 'basic_ostream'
    typedef basic_ostream<_CharT, _Traits>      ostream_type;
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1202:22: error: unknown type name 'ios_base'
                     ios_base& __iob, _Ch __fl);
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1182:22: error: member reference base type 'std::ostreambuf_iterator::ostream_type' (aka 'int') is not a structure or union
        : __sbuf_(__s.rdbuf()) {}
                  ~~~^~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iterator:1187:60: error: member reference base type 'std::ostreambuf_iterator::streambuf_type' (aka 'int') is not a structure or union
            if (__sbuf_ && traits_type::eq_int_type(__sbuf_->sputc(__c), traits_type::eof()))
                                                    ~~~~~~~^ ~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Sorting.o] Error 1

**When Looking at the h5pcc config :** 

(base) MacBook-Pro-de-David:Genesis-1.3-Version4-4.5.1 david$ h5pcc --showconfig
clang -I/usr/local/opt/include -L/usr/local/lib /usr/local/lib/libhdf5_hl.a /usr/local/lib/libhdf5.a -L/usr/local/opt/lib -lz -ldl -lm -I/usr/local/Cellar/open-mpi/4.0.5/include -L/usr/local/opt/libevent/lib -L/usr/local/Cellar/open-mpi/4.0.5/lib -lmpi
(base) MacBook-Pro-de-David:Genesis-1.3-Version4-4.5.1 david$

**Comment by svenreiche** [comment]
Unfortunately I have no access to MacOS X neither experience with CLANG, but can you try to use the dev branch? There we switch from gnu makefile to CMAKE, which should be much more user friendly regarding other environments and the right configuration.

**Comment by svenreiche** [comment]
Hi,
I am happy to report that I found the bug. I manage to compile genesis on macos x big sur using CLion with clang.
The error was that there are too many "using namespace std" in almost all header files. It is bad practice and this is actually a demonstration why it is. What happen is with "using namespace std" that the genesis include file "Time.h" became global and was used by the code wchar.h. It occurs on mac since the order of the search path is reversed. Anyhow the problem is solved by renaming the files Time.h and Time.cpp. so that wchar is including the right file. I will make a git commit for the major branch 'dev' with the renamed files.

I will then try a clean compilation on macos x to see if it works.  

Sorry that it took so long. Only now I got access to a macos X where I can try to compile it.

**Comment by svenreiche** [comment]
I updated the dev branch on github and cloned it to my mac (Big Sur). It compiled without any problems with clang and cmake, using the Clion IDE

**Comment by phdfong** [comment]
I have a huge project that has few hundreds of include directories, where i am using  file recursive search and loops to extract all the *.h* directories.

    FILE(GLOB_RECURSE files "*.h" "*.hpp")
    FOREACH(item ${files})
            get_filename_component(dirname ${item} DIRECTORY)
            WHILE(NOT ${dirname} STREQUAL ${CMAKE_CURRENT_SOURCE_DIR})
                #message("${dirname}")
                list(APPEND hpps ${dirname})
                get_filename_component(dirname ${dirname} DIRECTORY)
            ENDWHILE()
        ENDIF ()
    ENDFOREACH ()
    list(REMOVE_DUPLICATES hpps)
    foreach (hpp IN LISTS hpps)
        message(STATUS "include directories:  ${hpp}")
        include_directories(${hpp})
    endforeach()


first line of my code is #include <iostream> in main.cpp, it is actually causing the following error. However, If I don't overwhelmingly include the directories, it seems the simple main.cpp compiles ok.


Here is the errors:

```
In file included from /Userxxx/project/my_project_cpp/main.cpp:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/iostream:37:
....
....
....
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__memory/allocator.h:18:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/stdexcept:83:32: error: unknown type name 'string'
    explicit logic_error(const string&);

....
....
....
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/atomic:590:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__threading_support:457:11: error: use of undeclared identifier 'nanosleep'
   while (nanosleep(&__ts, &__ts) == -1 && errno == EINTR);
   
   ....
....
....
   In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/function.h:20:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__memory/shared_ptr.h:1729:1: error: no template named 'basic_ostream'
basic_ostream<_CharT, _Traits>&

....
....
....
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/iterator:593:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__iterator/istreambuf_iterator.h:46:13: error: no template named 'basic_streambuf'
    typedef basic_streambuf<_CharT,_Traits> streambuf_type;

....
....
....

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.



```

**Comment by svenreiche** [comment]
Dear Kenneth,

can you try the dev branch at github.
In the master branch there is still a bug on namespaces overwriting an include file from the standar dlibrary.

Best
Sven

-----------------------------------
Paul Scherrer Institut
Sven Reiche
WBBA/315
CH-5232 Villigen PSI

Telefon: +41 56 310 51 19
E-Mail: ***@***.******@***.***>***@***.***>***@***.***>

________________________________
