### ISSUE TITLE
[BUG] Makefile: -lmpi_cxx is needed to compile with some compiler installations

### ISSUE THREAD

**Issue by ZeugAusHH** [svenreiche/Genesis-1.3-Version4#48]
**Describe the bug**
Recent changes to Makefile can break compilation process. To investigate, additional compiler options were added to the final call to h5pcc:
h5pcc -Wl,--no-demangle -save-temps src/Main/mainwrap.cpp -o gencore -I./include -lgenesis13 -Llib -lm -lstdc++ -lfftw3
/software/gcc/9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: mainwrap.o: in function `_ZN3MPI9IntracommC2Ev':
mainwrap.cpp:(.text._ZN3MPI9IntracommC2Ev[_ZN3MPI9IntracommC5Ev]+0x14): undefined reference to `_ZN3MPI4CommC2Ev'
/software/gcc/9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: mainwrap.o: in function `_ZN3MPI9IntracommC2EP19ompi_communicator_t':
mainwrap.cpp:(.text._ZN3MPI9IntracommC2EP19ompi_communicator_t[_ZN3MPI9IntracommC5EP19ompi_communicator_t]+0x19): undefined reference to `_ZN3MPI4CommC2Ev'
/software/gcc/9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: mainwrap.o: in function `_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb':
mainwrap.cpp:(.text._ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb[_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb]+0x24): undefined reference to `ompi_mpi_cxx_op_intercept'
/software/gcc/9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: mainwrap.o:(.rodata._ZTVN3MPI3WinE[_ZTVN3MPI3WinE]+0x48): undefined reference to `_ZN3MPI3Win4FreeEv'
/software/gcc/9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: mainwrap.o:(.rodata._ZTVN3MPI8DatatypeE[_ZTVN3MPI8DatatypeE]+0x78): undefined reference to `_ZN3MPI8Datatype4FreeEv'
collect2: error: ld returned 1 exit status
make: *** [genesis] Error 1

**To Reproduce**
Modified final compiler call to:
h5pcc -Wl,--no-demangle -save-temps src/Main/mainwrap.cpp -o gencore -I./include -lgenesis13 -Llib -lm -lstdc++ -lfftw3
=> Issue is in mainwrap.o as conformed by
nm --demangle mainwrap.o | grep ompi_mpi_cxx_op_intercept
For the particular compiler configuration, symbol is provided by mpi_cxx.so:
nm -D /software/gcc/9.3.0/openmpi/3.1.6/lib/libmpi_cxx.so.40 | grep ompi_mpi_cxx_op_intercept

Information on system:
% lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

% module list
Currently Loaded Modulefiles:
  1) maxwell         2) gcc/9.3         3) openmpi/3.1.6   4) hdf5/1.10.6

% gcc --version
gcc (GCC) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by svenreiche** [comment]
I think there haven't been any problems once we switched to cmake. If still it occurs we can reopen it as an issue. For now I am closing the issue.
