### ISSUE TITLE
[BUG] dev: crash due to missing adjustment of size of beam->longESC during harmonic up-conversion process

### ISSUE THREAD

**Issue by ZeugAusHH** [svenreiche/Genesis-1.3-Version4#67]
Verified with commit id 6620483a4a708592c04cd3aa967ab21733ed7cb0

Example: Simulation with 128 slices running on mpisize=16

At the beginning we have in `EFieldSolver::longRange` in src/Core/EFieldSolver.cpp:
beam->beam.size() is 8
beam->longESC.size() is 8

After harmonic up-conversion by 50
beam->beam.size() is 400
beam->longESC.size() is still 8

In the `for` loop in `EFieldSolver::longRange` in src/Core/EFieldSolver.cpp, this results in write access beyond the end of the array during the `&track` following the upconversion. I have have done a few runs where it did not crash (which of course does not exclude adverse side effects of incorrect writes), but for a certain parameter configuration I was able to reproduce and finally track down the crash.

In the branch (not to be merged!) https://github.com/ZeugAusHH/Genesis-1.3-Version4/tree/cl_20230102__bugdiag I have stored a bit of diagnostics code I used.

**Comment by svenreiche** [comment]
Fixed
