### ISSUE TITLE
general question: unseeded SASE

### ISSUE THREAD

**Issue by rl3418** [svenreiche/Genesis-1.3-Version4#73]
I guess the field namelist defines the external seeding for SASE. I wish to know how could I simulate unseeded SASE. 

I sat radiation power in the field namelist to 0 (I guess this turns of the seeding), and turned on sponrad. However, when I tried to dump field data with track namelist, I got an error saying that H5Dwrite() cannot write data. The beam data is dumped as expected. I think this is because there is no field data. What is the correct way to simulate unseeded SASE?

**Comment by svenreiche** [comment]
You still have to define the field namelist but in it the power should be set to zero. Also in the setup namelist one has to set shotnoise to 1. The tag sponrad is only for the impact of energy losses due to the total emission of spontaneous radiation along the undulator. This can cause a detuning effect. but better to keep it off and have a flat undulator taper profile.  
Here is a snippet from a SASE simulation input deck:
&setup
rootname=Porthos
lattice=Porthos.lat
beamline=PORTHOS
lambda0=1e-10
gamma0=13700.6
delz=0.045000
shotnoise=1
npart=16384
nbins=8
&end

&time
slen=30e-6
sample=3
&end

&lattice
zmatch=9.5
&end


&field
power=0e3
dgrid=1.000000e-04
ngrid=201
waist_size=30e-6
&end

&beam
current=2000
delgam=1.957
ex=3.000000e-07
ey=3.000000e-07
&end

&track
bunchharm=3
&end

**Comment by rl3418** [comment]
Thanks a lot for the quick reply. What is bunchharm? I modified write and track namelists in the script you sent to see if I can dump field. H5Dwirte() still gives me an error saying that it cannot write data.

This is the modification I made:

&write
field=test
&end

&track
field_dump_step=1000
bunchharm=3
&end

**Comment by rl3418** [comment]
The code runs successfully if don't define the write namelist and field_dump_step. I tried to plot power v.s z via xgensis for a test run with two slices. xgenplot failed to plot to the graph as field data has shape 2*len(z)/2. I guess that's because the field is recorded separately for each slice. Do I just flatten the array?

**Comment by svenreiche** [comment]
Can you paste the error message. It is hard to decipher otherwise on what can be the problem.

One common problem is that there are not sufficient hard disk space left, since the dump files in time-dependent simulations can be huge (in the order of 100 GByte)

bunchharm=3 means that it calculates also the bunching factor for the output

Best,
Sven



-----------------------------------
Paul Scherrer Institut
Sven Reiche
WBBA/315
CH-5232 Villigen PSI

Telefon: +41 56 310 51 19
E-Mail: ***@***.******@***.***>***@***.***>***@***.***>

________________________________

**Comment by rl3418** [comment]
Emmm I failed to upload files and images for some reasons.
This is the error message I saw:
(base) runfeng@runfeng:~/Desktop/genesis$ ./gencore Porthos.in
---------------------------------------------
GENESIS - Version 4.5.1 has started...
compile info: compiled by runfeng 20230227T1527 from git commit ID 12d30f85c17d9f466ba61884dba2ff37eec9cd0d
Starting Time: Fri Mar  3 11:50:38 2023

MPI-Comm Size: 1 nodes

Parsing lattice file...
Setting up time window of 30 microns with 2 sample points...
Matching for periodic solution between z = 0 and z = 9.5 :
   betax (m) : 8.82088
   alphax    : -0.724138
   phix (deg): 44.4024
   betay (m) : 17.2028
   alphay    : 1.38775
   phiy (deg): 46.3371
Generating input radiation field for HARM = 1 ...
Generating input particle distribution...
Writing field distribution to file: test.fld.h5 ...
HDF5-DIAG: Error detected in HDF5 (1.10.4) MPI-process 0:
  #000: ../../../src/H5Dio.c line 336 in H5Dwrite(): can't write data
    major: Dataset
    minor: Write failed
  #001: ../../../src/H5Dio.c line 714 in H5D__write(): collective access for MPI-based driver only
    major: Dataset
    minor: Feature is unsupported
HDF5-DIAG: Error detected in HDF5 (1.10.4) MPI-process 0:
  #000: ../../../src/H5Dio.c line 336 in H5Dwrite(): can't write data
    major: Dataset
    minor: Write failed
  #001: ../../../src/H5Dio.c line 714 in H5D__write(): collective access for MPI-based driver only
    major: Dataset
    minor: Feature is unsupported

**Comment by rl3418** [comment]
These are the input files:

Porthos.in

&setup
rootname=Porthos
lattice=Porthos.lat
beamline=PORTHOS
lambda0=5e-6
gamma0=13700.6
delz=0.045000
shotnoise=1
npart=16384
nbins=8
&end

&time
slen=30e-6
sample=3
&end

&lattice
zmatch=9.5
&end

&field
power=0e3
dgrid=1.000000e-04
ngrid=201
waist_size=30e-6
&end

&beam
current=2000
delgam=1.957
ex=3.000000e-07
ey=3.000000e-07
&end


&write
field=test
&end

&track
field_dump_step=1000
bunchharm=3
&end

**Comment by rl3418** [comment]
Porthos.lat

D1: DRIFT = { l = 0.44};
D2: DRIFT = { l = 0.24};
QF: QUADRUPOLE = { l = 0.080000, k1= 2.000000 };
QD: QUADRUPOLE = { l = 0.080000, k1= -2.000000 };

UND: UNDULATOR = { lambdau=0.015000,nwig=266,aw=0.84853};

FODO: LINE={UND,D1,QF,D2,UND,D1,QD,D2};

Porthos: LINE={6*FODO};

**Comment by rl3418** [comment]
I reduced lambda0 to test if the field dump is working. There should only be a few slices. I had around 90GB of free space. I suppose that is enough for this trial run

**Comment by svenreiche** [comment]
It seems that you haven't compiled genesis with a MPI-complient HDF5 library. (often also called pHDF5). So Genesis cannot write files in multi-processor runs.
You can run it just as a single run or better compile with the corresponding libraries.

Best
Sven

-----------------------------------
Paul Scherrer Institut
Sven Reiche
WBBA/315
CH-5232 Villigen PSI

Telefon: +41 56 310 51 19
E-Mail: ***@***.******@***.***>***@***.***>***@***.***>

________________________________

**Comment by rl3418** [comment]
You mean I need a parallel version of HDF5. I used h5pcc -showconfig to check the features. My hdf5 library is indeed parallel. Is there a separate MPI flag that I need to enable.

**Comment by svenreiche** [comment]
Can you tell if CMAKE finds the parallel version. There should be a message if parallel hdf5 is supported or not

**Comment by rl3418** [comment]
I did not use cmake to compile the hdf5 library. I'm running the simulation on cluster computers with pre-compiled libraries. I used hpcc from hdf5/1.10.5-parallel and mpi/intel-2018.1.163 to compile genesis. 

Here are the configurations of hdf5/1.10.5-parallel: 

h5pcc -showconfig
            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.10.5
                  Configured on: Fri Feb 14 10:59:08 GMT 2020
                  Configured by: slacalle@login-6
                    Host system: x86_64-unknown-linux-gnu
              Uname information: Linux login-6 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
                       Byte sex: little-endian
             Installation point: /apps/hdf5/1.10.5

Compiling Options:
------------------
                     Build Mode: production
              Debugging Symbols: no
                        Asserts: no
                      Profiling: no
             Optimization Level: high

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables:
                        LDFLAGS: -L/apps/mpi/intel/2019.6.166/lib/release/ -lmpi -L/apps/mpi/intel/2019.6.166/lib -lmpifort
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries: -lz -ldl -lm
                       Archiver: ar
                       AR_FLAGS: cr
                         Ranlib: ranlib

Languages:
----------
                              C: yes
                     C Compiler: /apps/intel/2019.4/compilers_and_libraries_2019.4.243/linux/bin/intel64//icc ( Intel(R) C Intel(R) 64 Compiler Version 19.0.4.243 Build 20190416)
                       CPPFLAGS: -I/apps/mpi/intel/2019.6.166/include
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS:
                        C Flags:
                     H5 C Flags:   -std=c99 -Wcheck -Wall  -Wl,-s  -O3
                     AM C Flags:
               Shared C Library: yes
               Static C Library: yes


                        Fortran: yes
               Fortran Compiler: /apps/intel/2019.4/compilers_and_libraries_2019.4.243/linux/bin/intel64//ifort ( Intel(R) Fortran Intel(R) 64 Compiler Version 19.0.4.243 Build 20190416)
                  Fortran Flags: -I/apps/mpi/intel/2019.6.166/include
               H5 Fortran Flags:    -O3
               AM Fortran Flags:
         Shared Fortran Library: yes
         Static Fortran Library: yes

                            C++: no

                           Java: no


Features:
---------
                   Parallel HDF5: yes
Parallel Filtered Dataset Writes: yes
              Large Parallel I/O: yes
              High-level library: yes
                    Threadsafety: no
             Default API mapping: v110
  With deprecated public symbols: yes
          I/O filters (external): deflate(zlib)
                             MPE:
                      Direct VFD: no
                         dmalloc: no
  Packages w/ extra debug output: none
                     API tracing: no
            Using memory checker: no
 Memory allocation sanity checks: no
          Function stack tracing: no
       Strict file format checks: no
    Optimization instrumentation: no

**Comment by ZeugAusHH** [comment]
I think there is some confusion regarding the CMake question...

I guess the question by @svenreiche is referring to the CMake-based workflow used for the versions on the dev branch.
Here, when I compile it, CMake reports a line
```
-- Parallel HDF5 supported
```

However, the version used by @rl3418 is based on commit id https://github.com/svenreiche/Genesis-1.3-Version4/commit/12d30f85c17d9f466ba61884dba2ff37eec9cd0d and is still using the traditional `Makefile` approach to build.

I assume you are using a Linux distribution with modules functionality. If yes, could you please write (1) what is your distribution and (2) the output of `module list`?

**Comment by rl3418** [comment]
Yes, that is correct. I git cloned Genesis-1.3-Version4. 

I then loaded: 
1) intel-suite/2019.4 
2) gcc/5.4.0 
3)mpi/intel-2018.1.163  
4)hdf5/1.10.5-parallel

This is the makefile I used. (I only changed the file format so that it can be uploaded here) 
[Makefile.txt](https://github.com/svenreiche/Genesis-1.3-Version4/files/10929481/Makefile.txt)

**Comment by rl3418** [comment]
There is another slight point I wish to check. The guide on this github page says to run simulation execute 'genesis4 input-filename'. The command line executable 'genesis4' here is just 'gencore' added to the environment variable, right? The executable produced after compilation.

**Comment by svenreiche** [comment]
It is true that the executable after the compilation is gencore. There is the command "make install" which copies gencore to your local bin directory and rename it genesis4. But you can just use gencore or rename it as you wish

Best
Sven

-----------------------------------
Paul Scherrer Institut
Sven Reiche
WBBA/315
CH-5232 Villigen PSI

Telefon: +41 56 310 51 19
E-Mail: ***@***.******@***.***>***@***.***>***@***.***>

________________________________

**Comment by rl3418** [comment]
I reached out to the ICT staff maintaining the cluster. The problem is now resolved. Apparently the program is trying to leverage HDF5 parallel, when no parallel process is started. This can be resolved by running 'mpirun -n core_number ./gencore input_file'. rather than './gencore input_file'.

**Comment by svenreiche** [comment]
Perfect, it seems very much platform-depending on how single mpiruns are implemented.

I will close the issue
